### ISSUE TITLE
LGPL?

### ISSUE THREAD

**Issue by bhickey** [lidavidm/guile-rs#4]
Before 2009, Guile was provided with a linking exemption that basically reinvented the LGPL. It was subsequently relicensed under the LGPLv3. Would you consider releasing your bindings under the LGPL?

**Comment by lidavidm** [comment]
Ah shoot, I'm sorry I didn't see this earlier. I'll look into it, shouldn't be a problem.

**Comment by lidavidm** [comment]
To be honest, I haven't been working on this much (as you can tell), should probably pick it back up again.

**Comment by lidavidm** [comment]
Alright, I've just relicensed under LGPL, hope that helps.
